# Generated by Django 4.2 on 2023-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentage',
            name='image',
            field=models.ImageField(null=True, upload_to='rentage'),
        ),
    ]
