# Generated by Django 4.2 on 2023-04-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=255)),
                ('Secondname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('order_status', models.CharField(max_length=255)),
                ('Payment_method', models.CharField(max_length=255)),
                ('payment_complete', models.BooleanField(default=False)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.brand')),
            ],
        ),
    ]
