# Generated by Django 4.2 on 2023-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Transfer', 'Transfer')], default='Paystack', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel Payment', 'Cancel Payment'), ('Payment Received', 'Payment Received'), ('Order in progress', 'Order in progress'), ('Order Received', 'Order Received')], default='pending', max_length=255),
        ),
    ]
