# Generated by Django 4.1.7 on 2023-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0006_remove_order_payment_method_remove_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'petrol'), ('disel', 'diesel')], max_length=50, null=True),
        ),
    ]
