# Generated by Django 4.1.7 on 2023-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0007_brand_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='capacity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
