# Generated by Django 4.1.7 on 2023-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0009_alter_brand_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
