# Generated by Django 4.2 on 2023-05-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0010_alter_brand_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
