# Generated by Django 4.2 on 2023-05-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0011_alter_brand_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel')], max_length=50, null=True),
        ),
    ]
