# Generated by Django 4.2 on 2023-04-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
