# Generated by Django 4.2 on 2023-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_order_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
