# Generated by Django 4.2 on 2023-06-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_order_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='verified',
        ),
    ]
