# Generated by Django 4.2 on 2023-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=225)),
                ('Last_Name', models.CharField(max_length=225)),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=225)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
