# Generated by Django 4.2 on 2023-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack')], default='Paystack', max_length=50),
        ),
    ]
