# Generated by Django 4.2 on 2023-12-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_order_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
