# Generated by Django 4.2 on 2023-05-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='brand')),
                ('description', models.TextField(max_length=255)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('inventory', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('fuel', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel')], max_length=50, null=True)),
                ('capacity', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='rentage')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, null=True)),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('middlename', models.CharField(max_length=255, null=True)),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Cancel Payment', 'Cancel Payment'), ('Payment Received', 'Payment Received'), ('Order in progress', 'Order in progress'), ('Order Received', 'Order Received')], default='pending', max_length=255)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('booking', models.DateField(blank=True, null=True)),
                ('returnbooking', models.DateField(blank=True, null=True)),
                ('isAvailable', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('Paystack', 'Paystack'), ('Transfer', 'Transfer')], default='paystack', max_length=255)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrents.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrents.rentage'),
        ),
    ]
