# Generated by Django 4.2 on 2023-05-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='text',
            new_name='address',
        ),
    ]
