# Generated by Django 4.2 on 2023-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0004_remove_brand_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_days',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
