# Generated by Django 4.2 on 2023-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0005_order_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
