# Generated by Django 4.2 on 2023-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0006_alter_order_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
