# Generated by Django 4.2 on 2023-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0007_alter_order_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
