# Generated by Django 4.2 on 2023-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0009_alter_order_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
