# Generated by Django 4.2 on 2023-06-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0010_order_payment_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
