# Generated by Django 4.2 on 2023-06-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0011_rename_total_amount_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='amount',
            new_name='amounts',
        ),
    ]
