# Generated by Django 4.2 on 2023-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0012_rename_amount_brand_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
