# Generated by Django 4.2 on 2023-06-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0013_alter_brand_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
