# Generated by Django 4.2 on 2023-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0015_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
