# Generated by Django 4.2 on 2023-10-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0016_alter_slide_sub_title_alter_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='returnbooking',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_days',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
