# Generated by Django 4.2 on 2023-07-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0018_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='returnbooking',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_days',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
