# Generated by Django 4.2 on 2023-07-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0019_alter_order_booking_alter_order_returnbooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
