# Generated by Django 4.2 on 2023-07-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrents', '0026_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
